language: objective-c
osx_image: xcode7.3
xcode_project: ELog.xcodeproj
xcode_scheme: ELog
xcode_sdk: iphonesimulator9.3
env:
  global: 
    - FRAMEWORK_NAME=ELExport
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
script: 
   xctool -project ELog.xcodeproj -scheme ELog build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
